### ISSUE TITLE
has no exported member 'TransportConstructor' error on last version

### ISSUE THREAD

**Issue by vahid-sohrabloo** [improbable-eng/grpc-web#283]
When I update to 0.7.0  with last ts-protoc-gen give me this error
```
ERROR in src/messages/UV_pb_service.d.ts(553,55): error TS2694: Namespace '"/home/vahid/web_dashboard/node_modules/grpc-web-client/dist/typings/index".grpc' has no exported member 'TransportConstructor'.
```

**Comment by jonnyreeves** [comment]
Ah yes, thank you for raising. Ts-protoc-gen will need to be updated to create stubs that expect the new `grpc.Transport` type.

**Comment by jonny-improbable** [comment]
See https://github.com/improbable-eng/ts-protoc-gen/pull/139

**Comment by jonny-improbable** [comment]
[ts-prococ-gen@0.8.0](https://www.npmjs.com/package/ts-protoc-gen) has just been published which adds support for grpc-web-client v0.7.0+
